import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
#slope f'(a)
#tagent = slope*(x-a)+f(a)
#ex2_a (2,5)
x= sp.symbols ('x')
val=np.arange(-20,20,0.1)
fx_a = x*x +1
df_a =sp.diff(fx_a,x)
slope = df_a.subs(x,2)
y_tagent_a = slope*(x-2) + 5
f_val_a = sp.lambdify (x,fx_a,"numpy")(val)
f_tagent_a = sp.lambdify (x,y_tagent_a,"numpy")(val)
plt.plot(val,f_val_a,color = "red",label='fx')
plt.plot(val,f_tagent_a,color="blue",label='tagent')
plt.title("EX_2a",fontsize=15,color="green")
plt.grid(linestyle='--')
plt.legend()
plt.show()
#ex2_b (1,-1)
fx_b = x - 2*(x**2)
df_b = sp.diff(fx_b,x)
slope = df_b.subs(x,1)
y_tagent_b = slope*(x-1)-1
f_val_b = sp.lambdify(x,fx_b,"numpy")(val)
f_tagent_b = sp.lambdify(x,y_tagent_b,"numpy")(val)
plt.plot(val,f_val_b,color="red",label='fx')
plt.plot(val,f_tagent_b,color="blue",label='tagent')
plt.title("EX_2b",color="green")
plt.grid(linestyle='--')
plt.legend()
plt.show()
#ex2_c (3,3)
val=np.arange(2,10,0.133)
fx_c = x/(x-2)
df_c = sp.diff(fx_c,x)
slope = df_c.subs(x,3)
y_tagent_c = slope*(x-3)+3
f_val_c = sp.lambdify(x,fx_c,"numpy")(val)
f_tagent_c = sp.lambdify(x,y_tagent_c,"numpy")(val)
plt.plot(val,f_val_c,color="red",label='fx')
plt.plot(val,f_tagent_c,color="blue",label='tagent')
plt.title("EX_2c",color="green")
plt.grid(linestyle='--')
plt.legend()
plt.show()
#Ex2_d (2,2)
val=np.arange(1,5,0.133)
fx_d = 8/(x**2)
df_d = sp.diff(fx_d,x)
slope = df_d.subs(x,2)
y_tagent_d = slope*(x-2)+2
f_val_d = sp.lambdify(x,fx_d,"numpy")(val)
f_tagent_d = sp.lambdify(x,y_tagent_d,"numpy")(val)
plt.plot(val,f_val_d,color="red",label='fx')
plt.plot(val,f_tagent_d,color="blue",label='tagent')
plt.title("EX_2d",color="green")
plt.grid(linestyle='--')
plt.legend()
plt.show()
#Ex2_e(4,2)
val=np.arange(0,10,0.11)
fx_e = sp.sqrt(x)
df_e = sp.diff(fx_e,x)
slope = df_e.subs(x,4)
y_tagent_e = slope*(x-4)+2
f_val_e = sp.lambdify(x,fx_e,"numpy")(val)
f_tagent_e = sp.lambdify(x,y_tagent_e,"numpy")(val)
plt.plot(val,f_val_e,color="red",label='fx')
plt.plot(val,f_tagent_e,color="blue",label='tagent')
plt.title("EX_2e",color="green")
plt.grid(linestyle='--')
plt.legend()
plt.show()
#ex2_f (1,4)
val=np.arange(-3,5,0.001)
fx_f = x**3 + 3*x
df_f = sp.diff(fx_f,x)
slope = df_f.subs(x,1)
y_tagent_f = slope*(x-1)+4
f_val_f = sp.lambdify(x,fx_f,"numpy")(val)
f_tagent_f = sp.lambdify(x,y_tagent_f,"numpy")(val)
plt.plot(val,f_val_f,color="red",label='fx')
plt.plot(val,f_tagent_f,color="blue",label='tagent')
plt.title("EX_2f",color="green")
plt.grid(linestyle='--')
plt.legend()
plt.show()
#ex2_g (6,4)
val=np.arange(3,10,0.1)
fx_g = 8/sp.sqrt(x-2)
df_g = sp.diff(fx_g,x)
slope = df_g.subs(x,6)
y_tagent_g = slope*(x-6)+4
f_val_g = sp.lambdify(x,fx_g,"numpy")(val)
f_tagent_g = sp.lambdify(x,y_tagent_g,"numpy")(val)
plt.plot(val,f_val_g,color="red",label='fx')
plt.plot(val,f_tagent_g,color="blue",label='tagent')
plt.title("EX_2g",color="green")
plt.grid(linestyle='--')
plt.legend()
plt.show()
#ex2_h (3,2)
val=np.arange(-5,6,0.1)
fx_h =1+sp.sqrt(4-x)
df_h = sp.diff(fx_h,x)
slope = df_h.subs(x,3)
y_tagent_h = slope*(x-3)+2
f_val_h = sp.lambdify(x,fx_h,"numpy")(val)
f_tagent_h = sp.lambdify(x,y_tagent_h,"numpy")(val)
plt.plot(val,f_val_h,color="red",label='fx')
plt.plot(val,f_tagent_h,color="blue",label='tagent')
plt.title("EX_2h",color="green")
plt.grid(linestyle='--')
plt.legend()
plt.show()

