
from mpl_toolkits.mplot3d import Axes3D
from sympy import*
import numpy as np
import matplotlib.pyplot as plt
import math
global x,y
x,y = symbols('x,y')
def dothi(f):
  fa = lambdify((x,y),f,"numpy")
  xa,ya =np.meshgrid(np.arange(-1,1,0.2),np.arange(-1,1,0.1))
  za = fa(xa,ya)
  fig = plt.figure()
  ax = fig.add_subplot(111,projection ="3d")
  ax.plot_surface(xa,ya,za,cmap = plt.cm.ocean,alpha = 0.5)
  plt.xlabel("x0")
  plt.ylabel("y0")
  plt.title(str(f))
  plt.show()
  return 
def daoham_2xx(f):
  fx = diff(f,x,2)
  return fx
def daoham_2yy(f):
  fy = diff(f,y,2)
  return fy
def daoham_2yx(f):
  fyx = diff(diff(f,y,1),x,1)
  return fyx
def daoham_2xy(f):
  fxy = diff(diff(f,x,1),y,1)
  return fxy

   

#cau a
print("Cau a:")
f = x + y +x*y
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(f)
#cau b
print("Cau b:")
f = sin(x*y)
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(f)
dothi(fx)
dothi(fy)
dothi(fxy)
dothi(fyx)
#cau c
print("Cau c:")
f = x**2*y +cos(y) +y*sin(x)
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(f)
dothi(fx)
dothi(fy)
dothi(fxy)
dothi(fyx)

#cau d
print("Cau d:")
f = x*math.e**y +y +1
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(f)
dothi(fy)
dothi(fxy)
dothi(fyx)
#cau e 
print("Cau e:")
f =log(x+y)
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(fx)
dothi(fy)
dothi(fxy)
dothi(fyx)
#cau f 
print("Cau f:")
f = tan(y/x)**(-1)
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(fx)
dothi(fy)
dothi(fxy)
dothi(fyx)
#cau g
print("Cau g:")
f = (x**2)*tan(x*y)
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(fx)
dothi(fy)
dothi(fxy)
dothi(fyx)
#cau h 
print("Cau h:")
f = y**(math.e**(x**2)-y)
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(fx)
dothi(fy)
dothi(fxy)
dothi(fyx)
#cau i
print("Cau i:")
f = x*sin(y*x**2)
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(fx)
dothi(fy)
dothi(fxy)
dothi(fyx)
#cau j 
print("Cau j:")
f = (x-y)/(x+y)
fx = daoham_2xx(f)
fy = daoham_2yy(f)
fyx = daoham_2yx(f)
fxy = daoham_2xy(f)
print("fxx = {}".format(fx))
print("fyy = {}".format(fy))
print("fxy = {}".format(fxy))
print("fyx = {}".format(fyx))
dothi(fx)
dothi(fy)
dothi(fxy)
dothi(fyx)